# -*- coding: utf-8 -*-
"""SCT_ML_1_House_Price_Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2B8Ux3eI2jCuc2nDw93qzzB0KOzt0q-

# **Loading Data & Selecting Features**
"""

import pandas as pd
import numpy as np

# Loading the raw Kaggle dataset
df = pd.read_csv('Housing.csv')

# The assignment requires price, square footage, bedrooms, and bathrooms.
# Mapping 'area' as our square footage metric based on the data card.
target = 'price'
features = ['area', 'bedrooms', 'bathrooms']

# Filter to keep only the relevant columns for this experiment
df = df[[target] + features]

# Quick sanity check on shapes and null values before preprocessing
print(f"Dataset dimensions: {df.shape}")
df.head()

"""# **Handling Outliers with IQR**"""

# Real estate data always has extreme luxury properties that skew linear models.
# Implementing an IQR filter to trim the extreme tails of our distributions.

cleaned_df = df.copy()

for col in features:
    q1 = cleaned_df[col].quantile(0.25)
    q3 = cleaned_df[col].quantile(0.75)
    iqr = q3 - q1

    lower_cutoff = q1 - 1.5 * iqr
    upper_cutoff = q3 + 1.5 * iqr

    # Keeping only rows within standard statistical bounds
    cleaned_df = cleaned_df[(cleaned_df[col] >= lower_cutoff) & (cleaned_df[col] <= upper_cutoff)]

print(f"Rows removed after outlier cleanup: {len(df) - len(cleaned_df)}")
print(f"New dataset shape: {cleaned_df.shape}")

"""# **Engineering a Dynamic Layout Ratio**"""

# Simple linear correlations might miss how spaces are actually utilized.
# Creating a custom density feature: average area allocated per bedroom.
# Adding a small constant (0.1) to the denominator to prevent division-by-zero errors.

cleaned_df['area_per_bedroom'] = cleaned_df['area'] / (cleaned_df['bedrooms'] + 0.1)

# Reviewing the new engineered column structure
cleaned_df[['area', 'bedrooms', 'area_per_bedroom']].head()

"""# **Train-Test Splitting & Feature Scaling**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Splitting inputs from our target price variable
X = cleaned_df[['area', 'bedrooms', 'bathrooms', 'area_per_bedroom']]
y = cleaned_df['price']

# 80-20 split is standard for a dataset of this size (~500 rows)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling features because 'area' values are in the thousands,
# while room counts are single digits. This ensures weights train evenly.
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data successfully split and scaled.")

"""# **Training and Evaluation Metrics**"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# Fit the baseline linear regression baseline model
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

# Generate predictions on the validation test split
predictions = lr_model.predict(X_test_scaled)

# Measuring absolute dollar deviation and overall variance explained
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("--- Baseline Evaluation Results ---")
print(f"Mean Absolute Error: ${mae:,.2f}")
print(f"R-squared Score: {r2:.4f}")

print("\n--- Learned Feature Weights ---")
for feature, coef in zip(X.columns, lr_model.coef_):
    print(f"{feature}: {coef:+,.2f}")